import {DefaultTheme} from 'styled-components';

export const lightTheme: DefaultTheme = {
  fontFamily: 'Pretendard-Regular',
  fonts: {
    light: 'Pretendard-Light',
    medium: 'Pretendard-Medium',
    regular: 'Pretendard-Regular',
    semiBold: 'Pretendard-SemiBold',
    bold: 'Pretendard-Bold',
    extraBold: 'Pretendard-ExtraBold',
    primary: 'Pretendard-Regular',
  },
  fontSizes: {
    small: 12,
    regular: 14,
    medium: 16,
    large: 18,
    xLarge: 20,
    title: 24,
  },
  colors: {
    white: '#FFFFFF',
    text: '#2B2B2B',
    darkGray: '#828183',
    gray: '#50505055',
    lightGray: '#D3D3D3',
    red: '#E74C3C',
    green: '#5BAF63',
    blue: '#0E77EA',
    primary: '#8A715D',
    secondary: '#9B59B6',
    secondary2: '#F39C12',
    secondary3: '#E67E22',
    background: '#F5F4F5',
  },
};

export const darkTheme: DefaultTheme = {
  fontFamily: 'Pretendard-Regular',
  fonts: {
    light: 'Pretendard-Light',
    medium: 'Pretendard-Medium',
    regular: 'Pretendard-Regular',
    semiBold: 'Pretendard-SemiBold',
    bold: 'Pretendard-Bold',
    extraBold: 'Pretendard-ExtraBold',
    primary: 'Pretendard-Regular',
  },
  fontSizes: {
    small: 12,
    regular: 14,
    medium: 16,
    large: 18,
    xLarge: 20,
    title: 24,
  },
  colors: {
    white: '#2B2B2B',
    text: '#FFFFFF',
    darkGray: '#828183',
    gray: '#50505055',
    lightGray: '#A9A9A9',
    red: '#E74C3C',
    green: '#5BAF63',
    blue: '#0E77EA',
    primary: '#8A715D',
    secondary: '#3498DB',
    secondary2: '#F39C12',
    secondary3: '#E67E22',
    background: '#F5F4F5',
  },
};
