default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    sh "./android/gradlew test"  # gradlew가 있는 경로를 지정
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    sh "./android/gradlew clean assembleRelease"  # gradlew가 있는 경로를 지정
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh "./android/gradlew clean assembleRelease"  # gradlew가 있는 경로를 지정
    upload_to_play_store(track: 'internal') 
  end
end
