name: Build and Upload to TestFlight and Google Play

on:
  push:
    branches:
      - main  # 또는 master, 원하는 브랜치에 맞게 설정

jobs:
  build_ios:
    runs-on: macos-latest  # macOS 환경에서 실행
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        
      - name: Install dependencies
        run: |
          sudo gem install fastlane  # 관리자 권한으로 fastlane 설치
          sudo gem install bundler  # bundler 설치

      - name: Install gems with bundler
        run: |
          bundle install  # Gemfile에 정의된 의존성 설치

      - name: Build iOS app and upload to TestFlight
        run: |
          bundle exec fastlane beta  # bundle exec을 사용하여 fastlane 실행
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}  # GitHub Secrets에서 설정한 Apple ID
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}  # GitHub Secrets에서 설정한 App Store Connect 비밀번호

  build_android:
    runs-on: ubuntu-latest  # Android 빌드는 Ubuntu 환경에서 실행
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Java 버전 설정
          distribution: 'temurin'  # JDK 배포판 설정

      - name: Set up fastlane for Google Play deployment
        run: |
          sudo gem install fastlane  # 관리자 권한으로 fastlane 설치
          sudo gem install bundler  # bundler 설치

      - name: Install gems with bundler
        run: |
          bundle install  # Gemfile에 정의된 의존성 설치

      - name: Build Android app and upload to Google Play
        run: |
          cd android && ./gradlew clean assembleRelease  # Android 디렉토리로 이동 후 gradlew 실행
          bundle exec fastlane android beta  # bundle exec을 사용하여 fastlane 실행
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # GitHub Secrets에서 설정한 Google Play 서비스 계정 JSON 키
